apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: model-serving
  # https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#controller_summary
  annotations:
    kubernetes.io/ingress.class: "nginx" # which can be replaced by gce, gce-internal or istio
spec:
  rules:
  - host: 35.240.206.150.nip.io  # You can also use "35.240.206.150.nip.io", please refer to https://github.com/GoogleCloudPlatform/community/blob/master/archived/nginx-ingress-gke/index.md
    http:
      paths:
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 30000
      - path: /api/v1/openapi.json
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 30000
      - path: /api/easyllmops_conversation/conversation
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 30000