volumes:
    jenkins_home:

services:
    jenkins:
      build:
        context: .
        dockerfile: Dockerfile
      image: jenkins
      container_name: jenkins-server
      restart: unless-stopped
      privileged: true
      user: root
      ports:
        - 8082:8080
        - 50000:50000
      volumes:
        - jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
